server:
  port: 20001
logging:
  level:
    root: info
    com.yc: info
    org.springframework: info
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1

        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

        - id: web
          uri: lb://web
          predicates:
            - Path=/web/**
          filters:
            - StripPrefix=1
    nacos:
      discovery: localhost:8848
      username: nacos
      password: nacos

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"