server:
  port: 10000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: goods
          uri: lb://goods
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1
    nacos:
      discovery: localhost:8848
      username: nacos
      password: nacos

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"