server:
  port: 6000
  web:
    resources:
      #      SpringMVC指定静态页面存放位置
      static-locations: [classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,classpath:/static/,]

logging:
  level:
    root: info
    com.yhmall: info
    org.springframework.web: info
spring:
  cloud:
    nacos:
      discovery:
        #  namespace: yc125test   #服务的命名空间
        server-addr: localhost:8848
        username: nacos
        password: nacos
  application:
    name: web
management:
  endpoints:
    web:
      exposure:
        include: "*"
